### ISSUE TITLE
Move GBIAB pipeline to ensembl-genes repo

### ISSUE THREAD

**Issue by leannehaggerty** [Ensembl/ensembl-genes#8]
GBIAB
https://github.com/Ensembl/ensembl-analysis/blob/experimental/gbiab/scripts/genebuild/gbiab/gbiab.py

Supporting subsample script
https://github.com/Ensembl/ensembl-analysis/blob/experimental/gbiab/scripts/genebuild/gbiab/support_scripts/subsample_fastq.py

**Comment by williamstark01** [comment]
@fergalmartin what would the best place be for the `gbiab.py` script in this repository? Is it standalone so it could be placed in the scripts directory, or does is now or will most probably have auxiliary code files so that it made more sense to be placed in a dedicated `gbiab` directory?

**Comment by leannehaggerty** [comment]
Anno has it's own repo https://github.com/Ensembl/anno
